[package]
name = "fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ariadne = { version = "0.6.0", features = ["auto-color"] }
clap = { version = "4.5.53", features = ["derive"] }
walkdir = "2.5.0"
